dist: trusty
addons:
  chrome: stable
matrix:
  include:
    - language: python
      python:
        - "3.6.5"
      before_script:
        - pip install pipenv
        - pipenv install
        - cd server
      script:
        - pipenv run python test.py